[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
twirp = { path = "../crates/twirp" }

prost = "0.12"
prost-wkt = "0.5"
prost-wkt-types = "0.5"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.38", features = ["rt-multi-thread", "macros"] }

[build-dependencies]
twirp-build = { path = "../crates/twirp-build" }

fs-err = "2.8"
glob = "0.3.0"
prost-build = "0.12"
prost-wkt-build = "0.5"

[[bin]]
name = "example-client"
path = "src/bin/example-client.rs"
