[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
twirp = { path = "../crates/twirp" }
async-trait = "0.1"
hyper = { version = "0.14", features = ["full"] }
prost = "0.11"
prost-wkt = "0.3"
prost-wkt-types = "0.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.21.2", features = ["full"] }

[build-dependencies]
fs-err = "2.8"
glob = "0.3.0"
twirp-build = { path = "../crates/twirp-build" }
prost-build = "0.11"
prost-wkt-build = "0.3"

[[bin]]
name = "example-client"
path = "src/bin/example-client.rs"
