[toolchain]
channel = "1.70.0"
components = [ "rustfmt", "clippy", "llvm-tools-preview" ]
targets = [ "x86_64-unknown-linux-gnu", "x86_64-apple-darwin" ]
profile = "default"

# Details on supported fields: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
