[package]
name = "twirp"
version = "0.1.0"
authors = ["The blackbird team <support@github.com>"]
edition = "2021"

[features]
default = ["client", "server", "test-support"]
test-support = ["dep:async-trait", "dep:tokio"]
client = ["dep:reqwest", "dep:url"]
server = ["dep:hyper"]

[dependencies]
futures = "0.3"
prost = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

# For the client feature
reqwest = { version = "0.11", optional = true }
url = { version = "2.4", optional = true }

# For the server feature
hyper = { version = "0.14", features = ["full"], optional = true }

# For the test-support feature
async-trait = { version = "0.1", optional = true }
tokio = { version = "1.21.2", features = ["full"], optional = true }

[dev-dependencies]
tokio = { version = "1.28", features = ["full", "test-util"] }
async-trait = "0.1"
